[tool.poetry]
name = "bunkatopics"
version = "0.29"
# 0.28 Big Change compared to 0.26
description = ""
authors = ["Charles De Dampierre <charles.de-dampierre@hec.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
requests = "^2.28.1"
hdbscan = "0.8.28"
numpy = "1.21.5"
pandas = "1.4.1"
plotly = "5.6.0"
scikit-learn = "1.1.3"
sentence-transformers = "2.2.0"
spacy = "^3"
textacy = "0.12.0"
tqdm = "4.63.0"
umap-learn = "0.5.3"
xgboost = "1.6.2"
jupyterlab = "^3.5.1"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
